"""empty message

Revision ID: ffafb93c8bc4
Revises: 
Create Date: 2020-01-20 09:39:44.195522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffafb93c8bc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoreboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('lose', sa.Boolean(), nullable=True),
    sa.Column('tie', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoreboard')
    # ### end Alembic commands ###
